//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Laws')
export class LawsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Title: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('date', { nullable: true })
  EffectiveDate: Date;

  @Column('text', { nullable: true })
  Keywords: string;
}
